
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-19T14:09:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8b6c79b98f982dfc16322a4f0d29ede33655a3b",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
