
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-24T11:54:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "33e2af89318173c4b3b403e5f3b430fd3fcf88db",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
